openapi: 3.0.3
info:
  title: 4V ODS
  description: |-
    API Specification for 4V ODS 
  version: 1.0.0
servers:
  - url: https://localhost:8000
tags:
  - name: Iniciatives
    description: Everything about the iniciatives
  - name: ODS
    description: Everything about ODS
  - name: Goals
    description: Everything about Goals
  - name: Company
    description: Everything about Companies
  - name: Teacher
    description: Everything about Teachers
  - name: Module
    description: Everything about Modules
  - name: Degree
    description: Everything about Degrees
  
  
paths:
  /iniciatives:
    get:
      tags:
        - Iniciatives
      summary: get all iniciatives
      operationId: getIniciatives
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/iniciatives'          
        '400':
          description: Any problem in the Server
          
    post:
      tags:
        - Iniciatives
      summary: Add a new Iniciative
      description: Add a new Iniciative 
      operationId: addIniciative
      requestBody:
        description: Create a new iniciative
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newIniciative'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iniciatives'          
        '400':
          description: Invalid input
        '422':
          description: Validation exception
          
          
  /iniciatives/{iniciativesID}:
    put:
      tags:
        - Iniciatives
      summary: Update an existing iniciative
      description: Update an existing inciative by Id
      operationId: updateIniciative
      parameters:
        - name: iniciativesID
          in: path
          description: ID of activity
          required: true
          schema:
            type: integer
            format: int64
            
            
      requestBody:
        description: Update an existent iniciative
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newIniciative'


        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iniciatives'          

        '400':
          description: Invalid ID supplied
    delete:
      tags:
        - Iniciatives
      summary: Delete an exisiting iniciative
      description: Delete an iniciative by ID
      operationId: deleteIniciative
      parameters:
        - name: iniciativesID
          in: path
          description: ID of activity
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iniciatives'    
          
  /ods:
    get:
      tags:
        - ODS
      summary: get all ODS
      operationId: getAllODS
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ods'          
        '400':
          description: Any problem in the Server
  /goal:
    get:
      tags:
        - Goals
      summary: get all goals
      operationId: getAllGoals
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/goal'          
        '400':
          description: Any problem in the Server
  /company:
    get:
      tags:
        - Company
      summary: get all companies
      operationId: getAllCompanies
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/company'          
        '400':
          description: Any problem in the Server
  /teacher:
    get:
      tags:
        - Teacher
      summary: get all teachers
      operationId: getAllTeachers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/teacher'          
        '400':
          description: Any problem in the Server
  /module:
    get:
      tags:
        - Module
      summary: get all modules
      operationId: getAllModules
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/module'          
        '400':
          description: Any problem in the Server
  /degree:
    get:
      tags:
        - Degree
      summary: get all degrees
      operationId: getAllDegrees
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/degree'          
        '400':
          description: Any problem in the Server
          
components:
  schemas:
    iniciatives:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Iniciativa Test
        description:
          type: string
          example: En esta actividad se va a tratar sobre el hambre en el mundo
        start_date:
          type: string
          format: date
          example: "2025-03-01"
        end_date:
          type: string
          format: date
          example: "2025-06-01"
        hours:
          type: integer
          example: 20
        _active:
          type: boolean
          example: true
        school_year:
          type: string
          example: "2024-2025"
        innovative:
          type: boolean
          example: false
          
    ods:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        description:
          type: string
          example: Hambre en el mundo
        dimension:
          type: string
          example: Social
    goal:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        ods:
          type: object
          $ref: '#/components/schemas/ods'

             
        description:
          type: string
          example: Reducir la contaminación un 10%
    company:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        description:
          type: string
          example: Green Energy CO
    teacher:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Carlos Gutierrez
    module:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Software Development
        degree:
          type: object
          $ref: '#/components/schemas/degree'

              
    degree:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Computer Science
          
    newIniciative:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        start_date:
          type: string
          format: date
          example: "2025-06-01"
        end_date:
          type: string
          format: date
          example: "2025-08-01"
        hours:
          type: number
          format: int64
          example: 120
        school_year:
          type: string
          example: 2024-2025
        innovative:
          type: boolean

            
          
          
            
        
   
          
          
          
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 21
        description:
          type: string
          example: The name is mandatory
    
    