openapi: 3.0.3
info:
  title: 4V ODS
  description: |-
    API Specification for 4V ODS 
  version: 1.0.0
servers:
  - url: http://localhost:8000
tags:
  - name: Iniciatives
    description: Everything about the iniciatives
  - name: ODS
    description: Everything about ODS
  - name: Goals
    description: Everything about Goals
  - name: Company
    description: Everything about Companies
  - name: Teacher
    description: Everything about Teachers
  - name: Module
    description: Everything about Modules
  - name: Degree
    description: Everything about Degrees
  - name: Diffusion
    description: Everything about Diffusion
  
  
paths:
  /iniciatives:
    get:
      tags:
        - Iniciatives
      summary: get all iniciatives
      operationId: getIniciatives
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/iniciatives'          
        '400':
          description: Any problem in the Server
  /ods:
    get:
      tags:
        - ODS
      summary: get all ODS
      operationId: getAllODS
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ods'          
        '400':
          description: Any problem in the Server
  /goal:
    get:
      tags:
        - Goals
      summary: get all goals
      operationId: getAllGoals
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/goal'          
        '400':
          description: Any problem in the Server
  /company:
    get:
      tags:
        - Company
      summary: get all companies
      operationId: getAllCompanies
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/company'          
        '400':
          description: Any problem in the Server
  /teacher:
    get:
      tags:
        - Teacher
      summary: get all teachers
      operationId: getAllTeachers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/teacher'          
        '400':
          description: Any problem in the Server
  /module:
    get:
      tags:
        - Module
      summary: get all modules
      operationId: getAllModules
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/module'          
        '400':
          description: Any problem in the Server
  /degree:
    get:
      tags:
        - Degree
      summary: get all degrees
      operationId: getAllDegrees
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/degree'          
        '400':
          description: Any problem in the Server
  /diffusion:
    get:
      tags:
        - Diffusion
      summary: get all diffusions
      operationId: getAllDiffusion
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/diffusion'          
        '400':
          description: Any problem in the Server
          
components:
  schemas:
    iniciatives:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Iniciativa Test
        description:
          type: string
          example: En esta actividad se va a tratar sobre el hambre en el mundo
        start_date:
          type: string
          format: date
          example: "2025-03-01"
        end_date:
          type: string
          format: date
          example: "2025-06-01"
        hours:
          type: integer
          example: 20
        _active:
          type: boolean
          example: true
        school_year:
          type: string
          example: "2024-2025"
        innovative:
          type: boolean
          example: false
        type:
          type: string
          enum: 
            - proyecto
            - taller
            - charla
          example: proyecto
          
    ods:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        description:
          type: string
          example: Hambre en el mundo
        dimension:
          type: string
          example: Social
    goal:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        ods:
          type: object
          $ref: '#/components/schemas/ods'

             
        description:
          type: string
          example: Reducir la contaminación un 10%
    company:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        description:
          type: string
          example: Green Energy CO
    teacher:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Carlos Gutierrez
    module:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Software Development
        degree:
          type: object
          $ref: '#/components/schemas/degree'
    degree:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Computer Science
    diffusion:
      type: object
      properties:
        id: 
          type: integer
          format: int64
          example: 1
        type:
          type: string
          enum: 
            - instagram
            - facebook
            - twitter
          example: instagram
        link: 
          type: string
          example: https://www.facebook.com/sharer/sharer.php?
        iniciative:
          type: object
          $ref: '#/components/schemas/iniciatives'
          
            
        
   
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 21
        description:
          type: string
          example: The name is mandatory
    
    
