nelmio_cors:
    defaults:
        allow_origin: ['*']  # Permite todas las solicitudes (no recomendado en producción)
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
        allow_credentials: true  # Permite el uso de cookies o autenticación

    paths:
        '^/api/':  # Aplica CORS solo a rutas que comiencen con /api/
            allow_origin: ['https://example.com']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'OPTIONS']
            max_age: 3600
            allow_credentials: true
